'use client';

import { useState } from 'react';
import { Button } from '@/shared/ui/button';
import { Badge } from '@/shared/ui/badge';
import { useModuleWizardContext } from '../../../contexts/ModuleWizardContext';
import { createBaseModule } from '@/app/actions/admin/modules/base-modules';
import { createModuleImplementation } from '@/app/actions/admin/modules/module-implementations';

/**
 * Step 3: Revisão final e criação do módulo.
 */
export function ReviewCreateStep() {
  const { state, nextStep, updateConfig } = useModuleWizardContext();
  const [isCreating, setIsCreating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleCreate = async () => {
    setIsCreating(true);
    setError(null);
    
    try {
      const config = state.config;
      
      // Criar apenas o módulo base no catálogo
      console.debug('Criando base module...', config);
      const baseModuleResult = await createBaseModule({
        slug: config.basic?.slug || '',
        name: config.basic?.name || '',
        description: config.basic?.description || '',
        category: config.basic?.category || 'custom',
        icon: config.basic?.icon || 'Package',
        route_pattern: config.basic?.route_pattern || '',
        supports_multi_tenant: config.basic?.supports_multi_tenant ?? true,
        exclusive_tenant_id: config.basic?.supports_multi_tenant ? null : (config.basic?.exclusive_tenant_id || null),
        config_schema: {},
        permissions_required: [
          `read:${config.basic?.slug}`,
          `write:${config.basic?.slug}`
        ],
        dependencies: [],
        version: config.basic?.version || '1.0.0',
        tags: config.basic?.tags || [],
        auto_create_standard: config.basic?.auto_create_standard ?? false
      });

      if (!baseModuleResult.success) {
        throw new Error(baseModuleResult.error || 'Falha ao criar módulo base');
      }

      console.debug('✅ Base module criado:', baseModuleResult.data);

      // Salvar o ID do base module criado no contexto para uso no próximo step
      updateConfig('created_base_module_id' as any, baseModuleResult.data.id);
      updateConfig('created_base_module_data' as any, baseModuleResult.data);

      // Se auto_create_standard = true, criar implementação automaticamente
      if (config.basic?.auto_create_standard) {
        console.debug('🔄 Auto-criando implementação standard...');
        
        const autoGenerated = config.auto_generated;
        const implementationData = {
          base_module_id: baseModuleResult.data.id,
          name: `${config.basic.name} - Implementação Padrão`,
          implementation_key: autoGenerated?.implementation_key || `${config.basic.slug}-impl`,
          description: `Implementação padrão do módulo ${config.basic.name}`,
          component_path: autoGenerated?.component_path || `${config.basic.slug}Implementation`,
          version: config.basic.version || '1.0.0',
          component_type: 'file' as const,
          audience: 'generic' as const,
          complexity: 'standard' as const,
          priority: 'medium' as const,
          status: 'active' as const,
          is_default: true,
          template_type: 'dashboard' as const,
          template_config: {},
          config_schema_override: {},
        };

        const implResult = await createModuleImplementation(implementationData);
        
        if (!implResult.success) {
          console.warn('⚠️ Falha ao criar implementação automática:', implResult.error);
          // Não falhar completamente, apenas avisar e continuar
        } else {
          console.debug('✅ Implementação automática criada:', implResult.data);
          updateConfig('auto_created_implementation' as any, implResult.data);
          
          // Pular direto para o checklist se tudo deu certo
          updateConfig('implementation' as any, {
            id: implResult.data.id,
            implementation_key: implResult.data.implementation_key,
            component_path: implResult.data.component_path,
            audience: implResult.data.audience,
            ...implementationData
          });
        }
      }

      // Ir para o próximo step (será implementation-config ou client-config dependendo da configuração)
      nextStep();
    } catch (error) {
      console.error('❌ Erro ao criar módulo base:', error);
      setError(error instanceof Error ? error.message : 'Erro desconhecido ao criar módulo');
    } finally {
      setIsCreating(false);
    }
  };

  const config = state.config;

  return (
    <div className="space-y-6">
      {/* Revisão da Configuração */}
      <div className="p-6 bg-white border rounded-lg">
        <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
          📋 Revisão da Configuração
        </h3>
        
        <div className="grid grid-cols-2 gap-6">
          <div className="space-y-3">
            <h4 className="font-medium text-sm text-gray-500 uppercase tracking-wide">Informações Básicas</h4>
            <div className="space-y-2">
              <div className="flex justify-between">
                <span className="text-sm text-gray-600">Nome:</span>
                <span className="text-sm font-medium">{config.basic?.name}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-sm text-gray-600">Slug:</span>
                <code className="text-xs bg-gray-100 px-2 py-1 rounded">{config.basic?.slug}</code>
              </div>
              <div className="flex justify-between">
                <span className="text-sm text-gray-600">Categoria:</span>
                <Badge variant="secondary">{config.basic?.category}</Badge>
              </div>
              <div className="flex justify-between">
                <span className="text-sm text-gray-600">Tipo:</span>
                <Badge variant={config.type === 'custom' ? 'default' : 'outline'}>
                  {config.type === 'custom' ? 'Personalizado' : 'Padrão'}
                </Badge>
              </div>
            </div>
          </div>

          <div className="space-y-3">
            <h4 className="font-medium text-sm text-gray-500 uppercase tracking-wide">Configurações</h4>
            <div className="space-y-2">
              <div className="flex justify-between">
                <span className="text-sm text-gray-600">Multi-tenant:</span>
                <Badge variant={config.basic?.supports_multi_tenant ? 'default' : 'destructive'}>
                  {config.basic?.supports_multi_tenant ? 'Sim' : 'Exclusivo'}
                </Badge>
              </div>
              {config.type === 'custom' && (
                <div className="flex justify-between">
                  <span className="text-sm text-gray-600">Cliente:</span>
                  <Badge variant="default">{config.client?.clientType || 'Não definido'}</Badge>
                </div>
              )}
              {!config.basic?.supports_multi_tenant && (
                <div className="flex justify-between">
                  <span className="text-sm text-gray-600">Tenant:</span>
                  <span className="text-sm font-medium">{config.basic?.exclusive_tenant_id || 'A definir'}</span>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Descrição */}
        <div className="mt-6 space-y-2">
          <h4 className="font-medium text-sm text-gray-500 uppercase tracking-wide">Descrição</h4>
          <p className="text-sm text-gray-700 bg-gray-50 p-3 rounded-lg">
            {config.basic?.description}
          </p>
        </div>
      </div>

      {/* Error Display */}
      {error && (
        <div className="p-4 bg-red-50 border border-red-200 rounded-lg">
          <div className="flex items-start gap-3">
            <span className="text-red-500 text-lg">❌</span>
            <div>
              <h4 className="font-medium text-red-800">Erro ao criar módulo</h4>
              <p className="text-sm text-red-700 mt-1">{error}</p>
            </div>
          </div>
        </div>
      )}

      {/* Ação de Criação */}
      <div className="p-6 bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-200 rounded-lg">
        <div className="text-center space-y-4">
          <div className="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto">
            <span className="text-2xl">🚀</span>
          </div>
          <div>
            <h3 className="text-lg font-semibold text-blue-900">
              {config.basic?.auto_create_standard 
                ? 'Pronto para criar módulo completo' 
                : 'Pronto para criar o módulo base'
              }
            </h3>
            <p className="text-sm text-blue-700 mt-1">
              {config.basic?.auto_create_standard ? (
                <>
                  Isso criará o módulo base <strong>E</strong> uma implementação padrão automaticamente. 
                  Você poderá configurar clientes e personalizações nos próximos passos.
                </>
              ) : (
                'Isso criará uma entrada no catálogo de módulos. No próximo passo você configurará a implementação específica.'
              )}
            </p>
          </div>
          <Button 
            onClick={handleCreate} 
            disabled={isCreating}
            size="lg"
            className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-3"
          >
            {isCreating ? (
              <>
                <span className="mr-2">⏳</span>
                {config.basic?.auto_create_standard 
                  ? 'Criando módulo completo...' 
                  : 'Criando módulo base...'
                }
              </>
            ) : (
              <>
                <span className="mr-2">✨</span>
                {config.basic?.auto_create_standard 
                  ? 'Criar Módulo Completo' 
                  : 'Criar Módulo Base'
                }
              </>
            )}
          </Button>
          {isCreating && (
            <p className="text-xs text-blue-600 mt-2">
              Registrando no catálogo de módulos...
            </p>
          )}
        </div>
      </div>
    </div>
  );
}